#!/usr/local/bin/php
<?php declare(strict_types=1);

// swap line 1 with these depending on environment/docker.
// #/usr/local/bin/php
// #!/opt/homebrew/bin/php

// Check interface type, exit if not CLI.
if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

// Look for .env at the root directory
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

use CliExchangeRate\App;

$app = new App();

$app->registerController('list', new \App\Command\ExchangeRateListController($app));
$app->registerController('convert', new \App\Command\ExchangeRateConvertController($app));

$app->registerCommand('help', function (array $argv) use ($app) {
    $app->getOutputHandler()->out(
        message: 
            "\n" .
            "Commands: \n\n" .
            "   list:    " . \App\Command\ExchangeRateListController::$documentationString . "\n\n" .
            "   convert: " . \App\Command\ExchangeRateConvertController::$documentationString . "\n\n"
    );
});

$app->runCommand($argv);
